feat: 🎸 Add Prometheus metrics support
splunk/fabric-logger pull request #69
Opened 2020-12-08 20:39 UTC by ccordi

This adds support for Prometheus metrics via the
@splunkdlt/prometheus-scraper package.

2020-12-09 18:26 UTC, dexa187 commented on examples/prometheus-scraper/fabriclogger.yml
> +        - url: 'http://orderer1.example.com:7060/metrics'
Im wondering if we should pull these hostnames from the network.yaml connection profile that we read here https://github.com/splunk/fabric-logger/blob/master/src/fabric.ts#L62 to make configuration easier on the user?
Then we just have one entry in config to enable prometheus collection.

2020-12-09 18:32 UTC, ziegfried commented on examples/prometheus-scraper/fabriclogger.yml
> +        - url: 'http://orderer1.example.com:7060/metrics'
Yeah, absolutely! We actually talked about pretty much exactly that yesterday.

2020-12-16 20:05 UTC, ccordi commented on examples/prometheus-scraper/fabriclogger.yml
> +        - url: 'http://orderer1.example.com:7060/metrics'
Good idea. The latest version adds this.

2020-12-17 20:18 UTC, ziegfried requested changes

2020-12-17 20:18 UTC, ziegfried commented on src/config.ts
> +                port: flags['operations-port'] ?? defaults.prometheus?.port ?? '9090',
if the `--operations-port` flag only applies to prometheus, I think it should have "prometheus" in its name (some for the other, similar flags).

2020-12-17 20:18 UTC, ziegfried commented on src/config.ts
> +                path: flags['operations-path'] ?? defaults.prometheus?.path ?? 'metrics',
Should this be `'/metrics'`?

2020-12-17 20:18 UTC, ziegfried commented on src/connectionProfile.ts
> +export interface FabricConnectionProfile {
Let's put this in a `src/types` folder and add a comment that this contains generated types for the shape of a config file.

2020-12-17 20:18 UTC, ziegfried commented on src/prometheus.ts
> +export class Prometheus implements ManagedResource {
The name `Prometheus` is a bit vague. Let's call this something like `PrometheusMetricsScraper` and rename `PrometheusScraper` to something like `PrometheusEndpointScraper`

2020-12-17 20:18 UTC, ziegfried commented on src/index.ts
> +        const fabricListener = new FabricListener(checkpoint, config.fabric, prometheus, output);
I feel like the prometheus scraper should have it's own full lifecycle and not depend on FabricListener. From what I can tell the only shared resource is the connection profile yaml. I think it would be better if the prometheus scraper would separately load the yaml file and do initialization, processing and shutdown independently.

2020-12-17 20:19 UTC, ziegfried commented
Looks like there's a unit test that's failing.

2020-12-22 19:24 UTC, ccordi commented on src/cliflags.ts
> +        env: 'SPLUNK_EVENTS_INDEX',
I left the old env variable in for now. If we still want to change it, I think we can deprecate it or mark a breaking change when we update the docs.

2020-12-22 19:26 UTC, ccordi commented on src/config.ts
> +                port: flags['operations-port'] ?? defaults.prometheus?.port ?? '9090',
Replaced operations with prometheus, so it's now `--prometheus-port`.

2020-12-22 19:28 UTC, ccordi commented on src/prometheus.ts
> +export class Prometheus implements ManagedResource {
Done.

2021-01-06 06:16 UTC, ziegfried requested changes

2021-01-06 06:16 UTC, ziegfried commented on src/cliflags.ts
> +    'prometheus-index': flags.string({
I think we should remove the option to configure splunk metadata specifically for prometheus, since prometheus covers the whole metrics aspect and there is now splunk metadata specifically for metrics.

2021-01-06 06:16 UTC, ziegfried commented on src/config.ts
> +export interface PrometheusConfigFileSchema extends BasePrometheusConfigFileEndpoint {
We should remame `*ConfigFileSchema` to `*ConfigSchema`

2021-01-06 06:16 UTC, ziegfried commented on src/config.ts
> +    host: string;
This is redundant information, right? (since it's part of the URL as well)

We should possibly do a quick call to talk about that offline and see if we can untangle the inheritance structure and redundant information a bit.

2021-01-06 06:16 UTC, ziegfried commented on src/config.ts
> +                        host: url.hostname,
This isn't used anywhere, is it? Neither are port, path or protocol, correct?

2021-01-06 06:16 UTC, ziegfried commented on src/config.ts
> +                        'hyperledger_metrics',
We don't want this as the default.

2021-01-06 06:16 UTC, ziegfried commented on src/prometheus.ts
> +export interface BaseScraperConfig extends ScraperURLParts {
The "cooked" Scraper Config should probably not contain URL parts.

2021-01-06 06:16 UTC, ziegfried commented on src/prometheus.ts
> +        host: parsedEndpoint.hostname,
Those are not used anywhere, right?

2021-01-06 06:16 UTC, ziegfried commented on src/prometheus.ts
> +            scraper.scrape();
We'll need to `.catch(...)` any promise rejection this might cause.

2021-01-06 06:16 UTC, ziegfried commented on src/prometheus.ts
> +                this.output.logMultiMetrics({
Let's wrap this with a check if `this.active` is still `true` to avoid sending info to the output after shutdown.

2021-01-08 21:45 UTC, ccordi commented on src/prometheus.ts
> +export interface BaseScraperConfig extends ScraperURLParts {
Correct; they are now only left in the defaults.

2021-01-08 21:47 UTC, ccordi commented on src/config.ts
> +export interface PrometheusConfigFileSchema extends BasePrometheusConfigFileEndpoint {
Done.

2021-01-08 21:50 UTC, ccordi commented on src/config.ts
> +                        host: url.hostname,
Correct, the specific endpoints now require a full URL and will not accept any parts.

2021-01-08 21:51 UTC, ccordi commented on src/prometheus.ts
> +        host: parsedEndpoint.hostname,
Correct.

2021-01-08 21:51 UTC, ccordi commented on src/prometheus.ts
> +                this.output.logMultiMetrics({
Done.

2021-01-08 22:07 UTC, atoulme reviewed
Some typos

2021-01-08 22:07 UTC, atoulme commented on src/prometheus.ts
> +                        debug('Retrying avilability check on host=%s attempt=%d', url.host, attempt);
typo

2021-01-08 22:07 UTC, atoulme commented on src/prometheus.ts
> +        this.scrapeInterval = config.scrapeInterval ?? 10000;
Wasn't 10000 set as default?

2021-01-11 19:27 UTC, ccordi commented on src/prometheus.ts
> +                        debug('Retrying avilability check on host=%s attempt=%d', url.host, attempt);
Fixed.

2021-01-12 02:22 UTC, ccordi commented on src/prometheus.ts
> +            scraper.scrape().catch((e) => info('%s scraper encountered error:', name, e));
Done.

2021-01-12 20:08 UTC, ziegfried commented on src/config.ts
> +            }
We should emit a warning stating that we're ignoring a configured endpoint and why. Alternatively we could also throw an error.

2021-01-12 20:08 UTC, ziegfried commented on src/config.ts
> +        value: (DeepPartial<PrometheusEndpointConfigSchema> | undefined)[] | undefined
Why is this `DeepPartial`? The value we pass in down there is `PrometheusEndpointConfigSchema[] | undefined`

2021-01-12 21:20 UTC, ccordi commented on src/config.ts
> +                if (prometheusEndpointConfig && prometheusEndpointConfig?.url) {
¯\_(ツ)_/¯

2021-01-13 10:26 UTC, ziegfried approved these changes
🎉

2021-01-13 17:59 UTC, merged

2021-01-19 21:03 UTC, ccordi commented
:tada: This PR is included in version 3.1.0 :tada:

The release is available on [GitHub release](https://github.com/splunk/fabric-logger/releases/tag/3.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: