feat: 🎸 Add documentation generator and metavar support
splunk/fabric-logger pull request #71
Opened 2021-01-14 21:50 UTC by ccordi

2021-01-14 22:37 UTC, ccordi commented on docs/configuration.md
> +Fabriclogger has a dedicated flag `--print-config` to show the effective configuration after merging defaults, config file, environment variables and CLI flags.
This still needs to be added.

2021-01-19 20:13 UTC, ziegfried requested changes
Looking good. One more thing we'll want to do is to update the root README to refer to the configuration documents (or sections within those). We can also probably remove some of the content in the root README that is now redundant or outdated, such as the environment variables table at the bottom and instead just link to the CLI reference section.

2021-01-19 20:13 UTC, ziegfried commented on test/config/example1.fabriclogger.yaml
> +fabric:
Maybe we can slim this example down a bit and make it more real-world vs populating every possible option.

2021-01-19 20:13 UTC, ziegfried commented on config.schema.json
> +{
I tried validating the example config against this schema and it currently fails:

```
$ npx ajv-cli validate -s config.schema.json -d test/config/example1.fabriclogger.yaml --strict-types=false
npx: installed 27 in 1.656s
test/config/example1.fabriclogger.yaml invalid
[ { keyword: 'type',
    dataPath: '/prometheus/ordererPort',
    schemaPath: '#/properties/ordererPort/type',
    params: { type: 'string' },
    message: 'should be string' } ]
```

2021-01-20 23:30 UTC, ccordi commented on test/config/example1.fabriclogger.yaml
> +fabric:
I slimmed it down a bit.  Let me know if you think the prometheus options should be removed.

2021-01-20 23:31 UTC, ccordi commented on config.schema.json
> +{
This works now.

2021-01-20 23:58 UTC, ziegfried commented on test/config/example1.fabriclogger.yaml
> +fabric:
Looking good 👍

2021-01-21 00:01 UTC, atoulme approved these changes

2021-01-21 00:09 UTC, ziegfried approved these changes

2021-01-21 19:12 UTC, merged

2021-03-24 00:07 UTC, srv-gh-dlt commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on [GitHub release](https://github.com/splunk/fabric-logger/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: